import PersonSummary from '../components/summaries/PersonInfoSummary';
import SupplierInfoSummary from '../components/summaries/SupplierInfoSummary';

export const dummyCompanyNames: string[] = [
	'IT-Minds',
	'Kapacity',
	'Legoland',
	'Djurs Sommerland',
	'Google',
	'Facebook',
	'Apple',
	'Microsoft',
	'Amazon',
	'Netflix',
	'ExxonMobil',
	'AT&T',
	'General Motors',
	'Ford',
	'Chevrolet',
	'Walmart',
	'BP',
	'Royal Dutch Shell',
	'Coca-Cola',
	'PepsiCo',
	'PepsiCo',
	'Verizon',
	'Vodafone',
	'Vodafone',
	'Vodafone',
	'Vodafone',
	'China Mobile',
	'China Telecom',
	'China Telecom',
	'China Telecom',
	'China Unicom',
	'Nokia',
	'Ericsson',
	'Ericsson',
	'Ericsson',
	'Ericsson',
	'Intel',
	'IBM',
	'Qualcomm',
	'NVIDIA',
	'AMD',
	'ARM',
	'Oracle',
	'SAP',
	'Adobe',
	'Autodesk',
	'Autodesk',
	'Autodesk',
	'Autodesk',
	'Autodesk',
	'Autodesk',
	'Autodesk',
];
